// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYHIrfLP_lnOp3NvaB5heWiao5qBTn7s',
    appId: '1:635637982570:web:e66c3aba710ff2703eb113',
    messagingSenderId: '635637982570',
    projectId: 'flutterapp-fc807',
    authDomain: 'flutterapp-fc807.firebaseapp.com',
    storageBucket: 'flutterapp-fc807.appspot.com',
    measurementId: 'G-ZTDPNVTXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8taGwAPa2lSO5W04oLpzNSL1KLvhesI',
    appId: '1:635637982570:android:588ecee8f75349c03eb113',
    messagingSenderId: '635637982570',
    projectId: 'flutterapp-fc807',
    storageBucket: 'flutterapp-fc807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRl3DmkWlmOWTZ0hWmCH2GFwE4Q7hxU6E',
    appId: '1:635637982570:ios:df0b1cc3321d214d3eb113',
    messagingSenderId: '635637982570',
    projectId: 'flutterapp-fc807',
    storageBucket: 'flutterapp-fc807.appspot.com',
    iosClientId: '635637982570-52kkjvs7gqjfqfmbn0na0fj4dnshbhe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRl3DmkWlmOWTZ0hWmCH2GFwE4Q7hxU6E',
    appId: '1:635637982570:ios:df0b1cc3321d214d3eb113',
    messagingSenderId: '635637982570',
    projectId: 'flutterapp-fc807',
    storageBucket: 'flutterapp-fc807.appspot.com',
    iosClientId: '635637982570-52kkjvs7gqjfqfmbn0na0fj4dnshbhe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
